name: Deploy Airflow Project Infrastructure
on:
  workflow_dispatch:  
  push:
    branches:
      - main
    paths:
      - Airflow-Project/*
  pull_request:
    paths:
      - Airflow-Project/*

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  airflow-project-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-deploy-role
          aws-region: ap-south-1

      - name: Verify Identity (STS GetCallerIdentity)
        run: |
          aws sts get-caller-identity
      - name: Install terraform
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
          unzip terraform_1.5.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version
      - name: Terraform init
        run: 
          cd Airflow-Project/Infrastructure
          terraform init
      - name: Terraform plan
        run: 
          terraform plan
  airflow-job-apply:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    needs: airflow-project-plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-deploy-role
          aws-region: ap-south-1

      - name: Terraform apply
        run: 
          cd Airflow-Project/Infrastructure
          terraform apply -auto-approve
      
      

